### ISSUE TITLE
Locale is undefined

### ISSUE THREAD

**Issue by AndyCross** [microsoft/PowerBI-visuals-sampleBarChart#16]
options.host.locale is not defined when debugging through PowerBI service - is there a step to enable localization?

**Comment by helen508light** [comment]
Is it typed as VisualConstructorOptions at first? It must be options in init function, not in update (VisualUpdateOptions). It's working for me in powerbi Service.  Also, check is Settings-> Language specified in service.

**Comment by helen508light** [comment]
has been resolved
