### ISSUE TITLE
Fails on start

### ISSUE THREAD

**Issue by DanielOhYeah** [Microsoft/PowerBI-visuals-sampleBarChart#2]
I expected the visual to be ready out of the box. Do I have to manually install D3??

Building visual...
error TYPESCRIPT  File 'c:/.../typings.d.ts' not found
error TYPESCRIPT  /src/barchart.ts' (114,22)  cannot find namespace 'd3'
.
.<four errors like this>
.
error TYPESCRIPT  /src/barchart.ts' (114,22)  cannot find name 'd3'
<7 like this>

**Comment by jo-tham** [comment]
@DanielOhYeah did you run `npm i` and do you have [typings](https://github.com/typings/typings) installed?

**Comment by spatney** [comment]
@DanielOhYeah no you don't. npm i takes care of getting all dependencies and installing the right typings.
