### ISSUE TITLE
package failed.

### ISSUE THREAD

**Issue by reinhardtyang** [Microsoft/PowerBI-visuals-sampleBarChart#29]
I download the zip from github. when packaging the visual, I got the following error.
C:\Users\reyang\PBI\barchart>pbiviz package
 info   Building visual...
 error  TYPESCRIPT  /src/barChart.ts : (129,22) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (132,36) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (133,31) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (134,24) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (166,34) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (215,30) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (218,26) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (222,26) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (226,25) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (264,25) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/barChart.ts : (269,29) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (13,24) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (13,24) Parameter 'selection' of method from exported interface has or is using private name 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (39,24) Cannot find namespace 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (53,45) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (83,45) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (156,47) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (157,27) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (192,30) Cannot find name 'd3'.
 error  TYPESCRIPT  /src/tooltipServiceWrapper.ts : (198,40) Cannot find name 'd3'.

D3 is not available. How to fix it? thx.

**Comment by uve** [comment]
@reinhardtyang, try to run: **npm instal**l

**Comment by reinhardtyang** [comment]
I'm still trying use "npm install"
thanks a lot for your help.

**Comment by reinhardtyang** [comment]
I still have the following error:
C:\Users\reyang\PBI\barchart>pbiviz package
 info   Building visual...
 error  UNKNOWN { Error: ENOENT: no such file or directory, open 'C:\Users\reyang\PBI\barchart\node_modules\d3\d3.min.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at files.map.file (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:207:26)
    at Array.map (<anonymous>)
    at Promise (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:204:33)
    at new Promise (<anonymous>)
    at concatExternalJS (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:196:12)
    at compileTypescript.then (C:\Users\reyang\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\TypescriptCompiler.js:261:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\reyang\\PBI\\barchart\\node_modules\\d3\\d3.min.js' }

anyfile missing?

**Comment by uve** [comment]
What version of Typescript do you use?

**Comment by reinhardtyang** [comment]
D3 exists. but the file d3.min.js missing.

**Comment by reinhardtyang** [comment]
PBIviz is V1.10.1

**Comment by reinhardtyang** [comment]
C:\Users\reyang\PBI\barchart>pbiviz info
 info   visual.name.................. Bar Chart
 info   visual.displayName........... barChart
 info   visual.guid.................. PBI_CV_9894B302_1DFF_4A96_ABFE_BF8588197166
 info   visual.visualClassName....... BarChart
 info   visual.version............... 1.0.0
 info   visual.description...........
 info   visual.supportUrl............
 info   visual.gitHubUrl.............
 info   apiVersion................... 1.9.0
 info   author.name..................
 info   author.email.................
 info   assets.icon.................. assets/icon.png
 info   externalJS................... [ 'node_modules/d3/d3.min.js' ]
 info   style........................ style/visual.less
 info   capabilities................. capabilities.json

**Comment by reinhardtyang** [comment]
C:\Users\reyang\PBI\barchart>pbiviz info
 info   visual.name.................. Bar Chart
 info   visual.displayName........... barChart
 info   visual.guid.................. PBI_CV_9894B302_1DFF_4A96_ABFE_BF8588197166
 info   visual.visualClassName....... BarChart
 info   visual.version............... 1.0.0
 info   visual.description...........
 info   visual.supportUrl............
 info   visual.gitHubUrl.............
 info   apiVersion................... 1.9.0
 info   author.name..................
 info   author.email.................
 info   assets.icon.................. assets/icon.png
 info   externalJS................... [ 'node_modules/d3/d3.min.js' ]
 info   style........................ style/visual.less
 info   capabilities................. capabilities.json

**Comment by uve** [comment]
@reinhardtyang, please archive your source code and send it to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>
