### ISSUE TITLE
Static objects do not appear

### ISSUE THREAD

**Issue by abrice** [microsoft/PowerBI-visuals-sampleBarChart#3]
I copy the "module powerbi.extensibility.visual ..." code and the capabilities.json code and run it. The barchart works. No static object appears. objectEnumerationUtility.ts is located correctly. All that appears in the Objects well is Title/Background/Lock Aspect/General/Border.

I am using PowerBI Service (not desktop).

There should, based on the sample code, be a static 'show' object for 'enableAxis'.

[Edit] If I do a package build then the object ('enableAxis') appears in the well in the packaged vizualisation

![screen01](https://cloud.githubusercontent.com/assets/4556741/19363402/c5fa86ee-91e6-11e6-80a7-822cfe6acbd8.jpg)

**Comment by raananzvi** [comment]
This is a known issue on the debug visual.
We are aware of it

**Comment by WerlingM** [comment]
I've encountered this as well, both in this project and my custom visualization when running from the local development environment.  My changes to dataRoles appear fine in the fields well, but not the custom objects.

**Comment by amolkare** [comment]
Issue seems resolved, I can see static objects in property pane developer visual.

**Comment by chojrak11** [comment]
Any progress on this? Custom objects still don't work for me. Is there a workaround?

**Comment by uve** [comment]
it's fixed
