### ISSUE TITLE
Project doesnt work

### ISSUE THREAD

**Issue by kostenickj** [Microsoft/PowerBI-visuals-sampleBarChart#4]
steps:
1. downlaoded repo
2. ran "npm i" in folder that contains tsconfig.json
3. ran "pbiviz start" in that same folder
4. refresh to update. 

Blank screen.

here is a screenshot
![capture](https://cloud.githubusercontent.com/assets/17304343/19733714/ab1d0bb8-9b59-11e6-8362-b28d54bd9faf.PNG)

**Comment by kostenickj** [comment]
when debugging, dataviews in empty at this point which is returning an empty viewmodel.
![capture](https://cloud.githubusercontent.com/assets/17304343/19733902/6352f0f8-9b5a-11e6-9397-62c78b111725.PNG)

**Comment by LukaszPawlowski-MS** [comment]
You need to bind data to your visual.  The bar chart provides Category Data field and a Measure Data fields under the visualization pane.  Once you bind data to the visual, it should work.
