### ISSUE TITLE
can not run the project with `Error: <rect> attribute y: Expected length, "NaN".`

### ISSUE THREAD

**Issue by dash-alex** [microsoft/PowerBI-visuals-sampleBarChart#50]
![image](https://user-images.githubusercontent.com/46229829/53071997-cf9d6300-351e-11e9-9ecd-a2c6b8c74814.png)
![image](https://user-images.githubusercontent.com/46229829/53072007-d4faad80-351e-11e9-84ef-73ce5a74a07c.png)

where is the maxLocal in barChart.ts in line 66 come from?

**Comment by helen508light** [comment]
This values is from DataView.categorical.values[0].maxLocal
`
    export interface DataViewColumnAggregates {
        subtotal?: PrimitiveValue;
        max?: PrimitiveValue;
        min?: PrimitiveValue;
        average?: PrimitiveValue;
        median?: PrimitiveValue;
        count?: number;
        percentiles?: DataViewColumnPercentileAggregate[];

        /** Represents a single value evaluation, similar to a total. */
        single?: PrimitiveValue;

        /** Client-computed maximum value for a column. */
        maxLocal?: PrimitiveValue;

        /** Client-computed maximum value for a column. */
        minLocal?: PrimitiveValue;
    }`

Seems like this issue was resolved by last update
