### ISSUE TITLE
UI can't rander

### ISSUE THREAD

**Issue by saifulhq** [microsoft/PowerBI-visuals-sampleBarChart#53]
1. clone
2. npm install
3. pbiviz package
4. import to power bi desktop
5. setting category data

but the page just white like do nothing

**Comment by helen508light** [comment]
did you set Measure Data?

**Comment by koichino** [comment]
same as me. this doesn't render anything leaving white even when Category and Measure Data. Is this sample valid now?
The link below that has the link to this sample page is says "This documentation is deprecated. Please use new PowerBI Custom Visuals site instead."
https://github.com/Microsoft/PowerBI-visuals#developing-your-first-powerbi-visual

**Comment by helen508light** [comment]
issue has been resolved
