### ISSUE TITLE
Hyperlink is broken: Reference to Data Roles

### ISSUE THREAD

**Issue by bb0868** [microsoft/PowerBI-visuals-sampleBarChart#78]
On Page: https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/master/Tutorial/DataBinding.md

Under section: https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/master/Tutorial/DataBinding.md#adding-data-roles

The hyperlink referring to: For more information, see the section about **Data Roles**.

is broken.

current link assigned is:  https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Capabilities.md#define-the-data-fields-your-visual-expects---dataroles

Needs updating.

**Comment by helen508light** [comment]
fixed
