### ISSUE TITLE
Can't update to API Version 1.3 from command line

### ISSUE THREAD

**Issue by roseKQ** [Microsoft/PowerBI-visuals-sampleBarChart#9]
Hello - I want to make the tooltip changes etc and have been trying to update to API Version 1.3 with no success, I've tried... 

pbiviz update 

pbiviz update 1.3.0

It won't update though and runs an error, what am I doing wrong?

**Comment by roseKQ** [comment]
Here is the error message - 
error  UPDATE ERROR Error: Invalid API version: 1.3.0

It is the same if I want to update to 1.3.0 - I can however update to 1.2.0 ok

**Comment by roseKQ** [comment]
SORRY - needed to update version of the tools using 

npm install -g powerbi-visuals-tools

then could update to API version 1.3.0

**Comment by sahilanguralla** [comment]
`pbviz update` worked for me
